# Generated by Django 4.1.7 on 2023-03-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_tags_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/'),
        ),
    ]
